### PR TITLE
Use control simulation in yp-spur instead of ypspur_ros

### PR DESCRIPTION
**Pull request by at-wat**
Use yp-spur 1.21.0 or later.

### CODE REVIEW

**Comment by at-wat** [comment]
## [94] FAILED on noetic

<details><summary>Test failed</summary>


```
build/test_results/ypspur_ros/roslint-ypspur_ros.xml: 1 tests
build/test_results/ypspur_ros/rostest-test_test_joint_trajectory.xml: 1 tests
build/test_results/ypspur_ros/rosunit-test_joint_trajectory.xml: 2 tests, 0 errors, 2 failures, 0 skipped
Summary: 4 tests, 0 errors, 2 failures, 0 skipped
```
</details>

**Comment by at-wat** [comment]
## [95] FAILED on noetic

<details><summary>Test failed</summary>


```
build/test_results/ypspur_ros/roslint-ypspur_ros.xml: 1 tests
build/test_results/ypspur_ros/rostest-test_test_joint_trajectory.xml: 1 tests
build/test_results/ypspur_ros/rosunit-test_joint_trajectory.xml: 2 tests, 0 errors, 2 failures, 0 skipped
Summary: 4 tests, 0 errors, 2 failures, 0 skipped
```
</details>

**Comment by at-wat** [comment]
## [96] FAILED on noetic

```catkin_make tests``` failed

**Comment by at-wat** [comment]
## [97] PASSED on noetic

<details><summary>All tests passed</summary>


```
build/test_results/ypspur_ros/roslint-ypspur_ros.xml: 1 tests
build/test_results/ypspur_ros/rostest-test_test_joint_trajectory.xml: 1 tests
build/test_results/ypspur_ros/rosunit-test_joint_trajectory.xml: 2 tests
Summary: 4 tests, 0 errors, 0 failures, 0 skipped
```
</details>

**Comment by at-wat** [comment]
## [98] PASSED on noetic

<details><summary>All tests passed</summary>


```
build/test_results/ypspur_ros/roslint-ypspur_ros.xml: 1 tests
build/test_results/ypspur_ros/rostest-test_test_joint_trajectory.xml: 1 tests
build/test_results/ypspur_ros/rosunit-test_joint_trajectory.xml: 2 tests
Summary: 4 tests, 0 errors, 0 failures, 0 skipped
```
</details>

**Comment by at-wat** [comment]
## [101] PASSED on noetic

<details><summary>All tests passed</summary>


```
build/test_results/ypspur_ros/roslint-ypspur_ros.xml: 1 tests
build/test_results/ypspur_ros/rostest-test_test_joint_trajectory.xml: 1 tests
build/test_results/ypspur_ros/rosunit-test_joint_trajectory.xml: 2 tests
Summary: 4 tests, 0 errors, 0 failures, 0 skipped
```
</details>

**Comment by at-wat** [comment]
## [102] PASSED on noetic

<details><summary>All tests passed</summary>


```
build/test_results/ypspur_ros/roslint-ypspur_ros.xml: 1 tests
build/test_results/ypspur_ros/rostest-test_test_joint_trajectory.xml: 1 tests
build/test_results/ypspur_ros/rosunit-test_joint_trajectory.xml: 2 tests
Summary: 4 tests, 0 errors, 0 failures, 0 skipped
```
</details>

**Review by Taka-Kazu — APPROVED** [review]

**Pull request merged**
